apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: app-demo
  ports:
    - name: http 
      port: 8000
      targetPort: 8000
      nodePort: 31000
