apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: devops-tools
spec:
  selector:
    app: app-demo
  type: NodePort
  ports:
    - name: http 
      port: 3080
      targetPort: 3080
      nodePort: 3200

